name: ABI Update

on: 
  workflow_dispatch:

jobs:
  ABI-Update:
    name: Abi Update
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
      with:
          submodules: recursive
    - name: Install kernel build deps
      run: |
       sudo apt-get update && sudo apt-get install asciidoc-base automake bc bison cpio debhelper-compat \
       dh-python dwarves file flex gcc git kmod libdw-dev libelf-dev libiberty-dev libnuma-dev \
       libslang2-dev libssl-dev libtool lintian lz4 python3-minimal rsync sphinx-common xmlto zlib1g-dev zstd
    - name: ABI Update
      run: make abiupdate
  ABI-Check:
    name: Abi Check
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
      with:
          submodules: recursive
    - name: Install kernel build deps
      run: |
       sudo apt-get update && sudo apt-get install asciidoc-base automake bc bison cpio debhelper-compat \
       dh-python dwarves file flex gcc git kmod libdw-dev libelf-dev libiberty-dev libnuma-dev \
       libslang2-dev libssl-dev libtool lintian lz4 python3-minimal rsync sphinx-common xmlto zlib1g-dev zstd
    - name: ABI check
      run: debian/scripts/abi-check 
