name: Kernel Build

on: 
  pull_request:
    branches: [ master ]
  push:

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
      with:
          submodules: recursive
    - name: Install kernel build deps
      run: |
       sudo apt-get update && sudo apt-get install asciidoc-base automake bc bison cpio debhelper-compat \
       dh-python dwarves file flex gcc git kmod libdw-dev libelf-dev libiberty-dev libnuma-dev libpve-common-perl \
       libslang2-dev libssl-dev libtool lintian lz4 python3-minimal rsync sphinx-common xmlto zlib1g-dev zstd
    - name: Build Kernel
      run: make deb
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debs
        path: "*.deb"
